name: 🧹 Cargo Clippy Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-clippy:
    name: 🔍 Run Clippy Linter
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧪 Run Clippy
        env:
          PROTOC: ${{ env.PROTOC }}
        run: cargo clippy --workspace --tests --all-features -- -D warnings
